### ISSUE TITLE
A question about cutting shape from part

### ISSUE THREAD

**Issue by txtinman** [dprojects/Woodworking#16]
I want to create a panel with a 45 degree cut on one edge to use on a French Cleat wall. I've tried for an hour, but I can't figure it out. I built the panel using your workbench. Do I need a tool from another workbench? Should I make the part in the part or part design workbench and attach it using your workbench? Any help is appreciated.

**Comment by dprojects** [comment]
There is [router bit chamfer tool](https://github.com/dprojects/Woodworking/tree/master/Docs#router-bit---chamfer) to create quick 45 cut at the edge. If you make it at Cube, the Cube will be automatically transformed into Pad.
