### ISSUE TITLE
Ready to be added to Addon Manager?

### ISSUE THREAD

**Issue by luzpaz** [dprojects/Woodworking#2]
If so, you'd need a [package.xml](https://wiki.freecadweb.org/Package_Metadata) file.

**Comment by dprojects** [comment]
[package.xml](https://github.com/dprojects/Woodworking/blob/master/package.xml)

**Comment by luzpaz** [comment]
you can add macros as dependencies if you want...i think

**Comment by luzpaz** [comment]
Can you help me understand the odds and ends of how to install this workbench ? It looks like there are a series of macros that it depends on.

**Comment by luzpaz** [comment]
Please re-open this ticket as we didn't add this to the Addon Manager. I reiterate  

>Can you help me understand the odds and ends of how to install this workbench ? It looks like there are a series of macros that it depends on.

What are the perquisites ?

**Comment by Andor** [comment]
https://github.com/FreeCAD/FreeCAD-addons/pull/260
