### ISSUE TITLE
Some panels not working with Edit -> alignment

### ISSUE THREAD

**Issue by ergodicbreak** [dprojects/Woodworking#20]
I have kind of a weird issue I don't understand.

I have an existing model with many panels. I tried to align a panel with a sketch with Edit -> Alignment, and while the sketch was in the fixed object part of the Alignment window, there was nothing in the moveable object window (though I selected the panel and the sketch, only the sketch was in the Alignment view). 

However if I create a new panel, I _can_ align that panel with the sketch. 

Do you know of some condition that would happen where a panel would become un-alignable?

**Comment by dprojects** [comment]
> Do you know of some condition that would happen where a panel would become un-alignable?

If the panel is rotated. Please provide FreeCAD file sample and more description step by step. I am not sure what scenario you mean.

**Comment by ergodicbreak** [comment]
Thanks @dprojects, I'll try to recreate the issue in an easy to see way.

**Comment by dprojects** [comment]
should I close this issue?

**Comment by ergodicbreak** [comment]
Sure we can close for now, this isn't a critical blocking issue for me and I haven't had time to recreate a test case.
