### ISSUE TITLE
Workbench does not appear in FreeCAD drop-down list

### ISSUE THREAD

**Issue by horror-vacui** [dprojects/Woodworking#23]
Woodworking does not appear in the drop-down workbench list. Same results with View--> Workbenches. It also does not appear in the Addon Manager. Could you help me debug it? I've used FreeCAD a few times, but I am no expert. I've rebuilt FreeCAD because I had the same issue with the older (approx 1 year old) version.

------------------------------------------

Below are the steps of installation of the workbench:

I checked the location of the AppData with
`FreeCAD.ConfigDump()["UserAppData"]`

```
zoltan@adrian ~/.local/share/FreeCAD $   git clone https://github.com/dprojects/Woodworking.git
Cloning into 'Woodworking'...
remote: Enumerating objects: 2393, done.
remote: Counting objects: 100% (142/142), done.
remote: Compressing objects: 100% (104/104), done.
remote: Total 2393 (delta 86), reused 80 (delta 38), pack-reused 2251
Receiving objects: 100% (2393/2393), 72.51 MiB | 11.16 MiB/s, done.
Resolving deltas: 100% (1376/1376), done.
```

```
OS: Manjaro Linux (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.2.29603 (Git)
Build type: Release
Branch: makepkg
Hash: 930dd9a76203a3260b1e6256c70c1c3cad8c5cb8
Python 3.10.9, Qt 5.15.8, Coin 4.0.1, Vtk 9.2.6, OCC 7.6.3
Locale: English/United States (en_US)
Installed mods: 
  * fasteners 0.4.56
  * CADExchanger
  * lattice2 1.0.0
  * DynamicData 2.46.0
  * OpticsWorkbench 1.0.9
  * LCInterlocking
  * Assembly4 0.50.2
  * ExplodedAssembly
  * Estimate 0.1.2
  * parts_library
```

**Comment by dprojects** [comment]
You need to have Mod folder inside FreeCAD folder: [Woodworking installation](https://github.com/dprojects/Woodworking#installation)

Please reopen this issue if this not solved your problem.
