### ISSUE TITLE
toCut uses template already used by TechDraw causing serious issue, when the toPrint is deleted

### ISSUE THREAD

**Issue by przemhb** [dprojects/Woodworking#25]
In my project I have a few technical drawings created in the TechDraw. I have noticed, that when I run Woodworking's getDimensions function then the resulting toPrint uses the same template as the first TechDraw drawing. As a result, when I delete the toPrint with "its" template, then the template gets removed from the TechDraw page. It causes serious issue. Missing template cannot be added, project has error, cannot be recomputed and properties are no longer displayed. Furthermore the TechDraw cannot be even deleted to start from scratch. Recovering from the issue is really hard.

![image](https://github.com/dprojects/Woodworking/assets/9753991/bdc15b80-7c4a-4e1a-a0e9-59db7aa99841)

**Comment by przemhb** [comment]
FreeCad 0.20.2, Woodworking 0.20.

**Comment by dprojects** [comment]
Hi, can you attach file sample? No real-life project, just sample to reproduce the problem, I will look into that later what is going on there.

**Comment by przemhb** [comment]
Here you have it:

[template-issue.zip](https://github.com/dprojects/Woodworking/files/12207787/template-issue.zip)

Run getDimensions with default settings and then delete template from the "toPrint" and notice it gets deleted from the "01.01'A Blat" technical drawing. Apparently "toPrint" links to already existing template instead of creating a new one.

**Comment by dprojects** [comment]
Has been fixed by: [fix template overwrite ](https://github.com/dprojects/getDimensions/commit/9efb90c2ecfac136403a2361c65e06609ac21575). Thanks.
