### ISSUE TITLE
Typos found in source

### ISSUE THREAD

**Issue by luzpaz** [dprojects/Woodworking#3]
```
./Tools/sheet2export/sheet2export.py:743: conroller ==> controller
./Tools/getDimensions/getDimensions.py:568: varable ==> variable
./Tools/getDimensions/getDimensions.py:863: egde ==> edge
./Tools/getDimensions/getDimensions.py:870: colomn ==> column
./Tools/getDimensions/getDimensions.py:937: obejct ==> object
./Tools/getDimensions/getDimensions.py:1559: grup ==> group
./Tools/scanObjects/scanObjects.py:47: hight ==> height, high
```

**Comment by dprojects** [comment]
outdated, currently it is: 

./Tools/scanObjects.py:525: outpust ==> output, outputs
./Tools/sheet2export.py:743: conroller ==> controller
./Tools/MagicPanels/MagicPanels.py:768: Vertexes ==> Vertices
./Tools/MagicPanels/MagicPanels.py:775: Vertexes ==> Vertices
./Tools/MagicPanels/MagicPanels.py:830: Vertexes ==> Vertices
./Tools/MagicPanels/MagicPanels.py:835: Vertexes ==> Vertices
./Tools/MagicPanels/MagicPanels.py:912: Vertexes ==> Vertices
./Tools/MagicPanels/MagicPanels.py:921: Vertexes ==> Vertices
./Tools/MagicPanels/MagicPanels.py:928: Vertexes ==> Vertices
./Tools/MagicPanels/MagicPanels.py:1004: Vertexes ==> Vertices
./Tools/MagicPanels/MagicPanels.py:1009: Vertexes ==> Vertices
./Tools/MagicPanels/MagicPanels.py:1014: Vertexes ==> Vertices
./Tools/MagicPanels/MagicPanels.py:1086: Vertexes ==> Vertices
./Tools/MagicPanels/MagicPanels.py:1091: Vertexes ==> Vertices
./Tools/MagicPanels/MagicPanels.py:1096: Vertexes ==> Vertices
