### ISSUE TITLE
The data in the showSpaceModel window is poorly visible if dark mode is used.

### ISSUE THREAD

**Issue by mad-max-traveller** [dprojects/Woodworking#31]
The data in the showSpaceModel window is poorly visible if dark mode is used. This is also the case in other tools similar to showSpaceModel.

![изображение](https://github.com/dprojects/Woodworking/assets/35477964/9732e7f6-df1e-455a-8a52-744e793ce1ae)

![изображение](https://github.com/dprojects/Woodworking/assets/35477964/3db22311-d130-45c3-a0da-61df9c5f275e)

**Comment by dprojects** [comment]
any idea how to fix it? you can always invent theme color which will be not visible, I can only adjust for base themes

**Comment by dprojects** [comment]
I changed the background into red, so now should be fine with classic and dark theme.
Feel free to re-open this issue if you think this should be changed. Thanks!
