### ISSUE TITLE
magicDriller not working in Freecad v0.22

### ISSUE THREAD

**Issue by blob42** [dprojects/Woodworking#44]
Hi, 

Thanks for your efforts with this workbench. I am using freecad 0.22 and the magicDrill does not work as intended. The drill bits appear and move as expected but when I press on `drill below drill bits` a new Part is created with an empty sketch named `Pattern, Panel XX` See the screenshot below

![2024-04-29-044445_2687x1272_scrot](https://github.com/dprojects/Woodworking/assets/210457/205e734e-6678-4fa3-81d6-6cc7adc33e51)

**Comment by blob42** [comment]
Sorry It works I just realized I was using it the wrong way

**Comment by dprojects** [comment]
this is still an issue? I can't reproduce this problem... please reopen this issue if there is still something unsolved.
